AppLogin/urls.py
from django.urls import path
from AppLogin import views
app_name = 'AppLogin'
urlpatterns = [
    path('signup/', views.signupUser, name='signup'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('profile/', views.profileUser, name='profile'),
    path('profile/edit/', views.editProfile, name='editprofile'),
]

fullEcommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('AppLogin.urls')),
]

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppLogin/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class MyUserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Email Fields must not be empty')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError("Superuser must have is_staff = True")
        if extra_fields.get('is_superuser') is not True:
            raise ValueError("Superuser must have is_superuser = True")
        return self._create_user(email, password, **extra_fields)
    
class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=False)
    is_staff = models.BooleanField(
        gettext_lazy('staff status'),
        default=False,
        help_text=gettext_lazy('Designates whether the user can login into administration site')
    )
    is_active = models.BooleanField(
        gettext_lazy('active'),
        default=True,
        help_text=gettext_lazy('Check/Uncheck this to unban/ban a user.')
    )
    is_seller = models.BooleanField(
        gettext_lazy('Seller Status'),
        default=False,
        help_text=gettext_lazy('Designates whether the user is selling products.')
    )
    USERNAME_FIELD = 'email'
    objects = MyUserManager()
    def __str__(self):
        return self.email

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='userprofile')
    username = models.CharField(max_length=264, blank=True)
    fullname = models.CharField(max_length=264, blank=True)
    address_1 = models.TextField(max_length=300, blank=True)
    city = models.CharField(max_length=40, blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    country = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname
    
    def is_complete(self):
        allfields = [x.name for x in self._meta.get_fields()]
        for field in allfields:
            value = getattr(self, field)
            if value is None or value == '':
                return False
        return True

# @receiver(post_save, sender=User)
# def create_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_profile(sender, instance, **kwargs):
#     instance.userprofile.save()

AppLogin/forms.py
from django import forms
from .models import User, Profile
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    choices = (
        ('', "Is this a seller account?"),
        ('1', 'Yes'),
        ('0','No'),
    )
    type = forms.ChoiceField(label='', choices=choices, required=True)
    email = forms.EmailField(label="", required=True, widget=forms.TextInput(attrs={
        'placeholder':'Email Address',
    }))
    password1 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={
        'placeholder':'Type your password'
    }))
    password2 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={
        'placeholder':'Type your password again'
    }))
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']
class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        exclude = ['user']
        labels = {
            'username':"",
            'fullname':'',
            'address_1':'',
            'city':'',
            'country':'',
            'phone':'',
            'zipcode': ''
        }
        widgets = {
            'username':forms.TextInput(attrs={
                'placeholder':'Username'
            }),
            'fullname':forms.TextInput(attrs={
                'placeholder':'Full Name'
            }),
            'address_1':forms.TextInput(attrs={
                'placeholder':'Detailed Address'
            }),
            'city':forms.TextInput(attrs={
                'placeholder':'City'
            }),
            'country':forms.TextInput(attrs={
                'placeholder':'Country'
            }),
            'phone':forms.TextInput(attrs={
                'placeholder':'Phone Number'
            }),
            'zipcode':forms.TextInput(attrs={
                'placeholder':'Zipcode'
            }),
        }

AppLogin/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .forms import SignUpForm, ProfileForm
from .models import Profile, User
from django.contrib import messages
# Create your views here.
def signupUser(req):
    form1 = SignUpForm()
    form2 = ProfileForm()
    if(req.method == 'POST'):
        form1 = SignUpForm(req.POST)
        form2 = ProfileForm(req.POST)
        if (form1.is_valid()) and (form2.is_valid()):
            user = form1.save(commit=False)
            acc_type = form1.cleaned_data.get('type')
            user.is_seller = True if acc_type == '1' else False
            user.save()
            profile = form2.save(commit=False)
            profile.user = user
            profile.save()
            messages.success(req, "Account Profile Created Successfully")
            return HttpResponseRedirect(reverse('AppLogin:login'))
    return render(req, 'AppLogin/signup.html', context={'user':form1, 'profile':form2})

def loginUser(req):
    form = AuthenticationForm()
    if req.method=='POST':
        form = AuthenticationForm(data=req.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(req, user)
                messages.success(req, 'You have successfully logged in!')
                return HttpResponseRedirect(reverse('AppLogin:profile'))
    return render(req, 'AppLogin/login.html', context={'form':form})
@login_required
def logoutUser(req):
    logout(req)
    messages.warning(req, "You have been logged out")
    return HttpResponseRedirect(reverse('AppLogin:login'))
@login_required
def profileUser(req):
    profile = Profile.objects.get(user=req.user)
    return render(req, 'AppLogin/profile.html', context={'profile':profile})
@login_required
def editProfile(req):
    profile = Profile.objects.get(user=req.user)
    form = ProfileForm(instance=profile)
    if req.method=='POST':
        form = ProfileForm(req.POST, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(req, 'Successfully updated your profile')
            form = ProfileForm(instance=profile)
            return HttpResponseRedirect(reverse('AppLogin:profile'))
    return render(req, 'AppLogin/editprofile.html', context={'form':form})

templates/AppLogin/editprofile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  
{% endblock title %}
{% block body %}
  <h3 class="mb-3"></h3>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary mt-2">Update profile!</button>
  </form>
{% endblock body %}

templates/AppLogin/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  Login to your account!
{% endblock title %}
{% block body %}
  <h3 class="mb-3">Login to your account!</h3>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary mt-2">Login</button>
  </form>
{% endblock body %}

templates/AppLogin/profile.html
{% extends "base.html" %}
{% block title %}
  Profile of {{profile.fullname}}
{% endblock title %}
{% block body %}
<div class="d-flex justify-content-between align-items-center">
    <table class="table table-bordered">
        <thead>
            <th colspan="2">Personal Info</th>
        </thead>
        <tbody>
            <tr>
                <td>Username</td>
                <td>{{profile.username}}</td>
            </tr>
            <tr>
                <td>Full Name</td>
                <td>{{profile.fullname}}</td>
            </tr>
            <tr>
                <td>Email Address</td>
                <td>{{user.email}}</td>
            </tr>
            <tr>
                <td>Contact Address</td>
                <td>{{profile.address_1}}</td>
            </tr>
            <tr>
                <td>Phone Number</td>
                <td>{{profile.phone}}</td>
            </tr>
            <tr>
                <td>Zipcode</td>
                <td>{{profile.zipcode}}</td>
            </tr>
            <tr>
                <td>City</td>
                <td>{{profile.city}}</td>
            </tr>
            <tr>
                <td>Country</td>
                <td>{{profile.country}}</td>
            </tr>
        </tbody>
    </table> 
    </div>
    <a href="{% url 'AppLogin:editprofile' %}" class="btn btn-primary">Edit your profile!</a>
{% endblock body %}

templates/AppLogin/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  Create a account!
{% endblock title %}
{% block body %}
  <h3 class="mb-3">Create a account!</h3>
  <form action="" method="POST">
    {% csrf_token %}
    {{ user|crispy }}
    {{ profile|crispy }}
    <button type="submit" class="btn btn-primary mt-2">Create Account</button>
  </form>
{% endblock body %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js' integrity='sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL' crossorigin='anonymous'></script>
  <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN' crossorigin='anonymous'>
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css' integrity='sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==' crossorigin='anonymous' referrerpolicy='no-referrer' />
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' integrity='sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==' crossorigin='anonymous' referrerpolicy='no-referrer' />
    <title>
        {% block title %}
          Django E-commerce project
        {% endblock title %}
    </title>
</head>
<body>
  
  {% include "navbar.html" %}
  <div class="container">
    {% block body %}
      
    {% endblock body %}
  </div>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
    <div class="container">
      <a class="navbar-brand" href="">Django E-Commerce Project</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        {% if user.is_authenticated %}
        <ul class="navbar-nav align-items-center gap-4">
            <li class="nav-item dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                    {{user.userprofile.fullname}}
                  </button>
                  <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
                    {% if user.is_seller %}
                      <li><a class="dropdown-item" href="">Add Products</a></li>
                    {% endif %}
                    <li><a class="dropdown-item" href="{% url 'AppLogin:profile' %}">Profile</a></li>
                    <div class="dropdown-divider"></div>
                    <li><a class="dropdown-item" href="{% url 'AppLogin:logout' %}">Logout</a></li>
                  </ul>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav align-items-center gap-4">
            <li class="nav-item"><a href="{% url 'AppLogin:login' %}" class="nav-link">Login</a></li>
            <li class="nav-item"><a href="{% url 'AppLogin:signup' %}" class="nav-link">Signup</a></li>
        </ul>
        {% endif %}
      </div>
    </div>
  </nav>